namespace Model.Entities;

public class AppUser {
	public Guid Id { get; set; } // autogenerated
	public string Username { get; set; } = null!;
	public string PasswordHash { get; set; } = null!;
	public DateTimeOffset CreatedAt { get; set; } // autogenerated

	public ICollection<Media> MediaCreated { get; set; } = new List<Media>();
	public ICollection<Rating> Ratings { get; set; } = new List<Rating>();
	public ICollection<RatingLike> RatingLikes { get; set; } = new List<RatingLike>();
	public ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();
}