namespace Model.Entities;

public class Genre {
	public Guid Id { get; set; } // autogenerated
	public string Name { get; set; } = null!;

	public ICollection<MediaGenre> MediaGenres { get; set; } = new List<MediaGenre>();
}