namespace Model.Entities;

public class Media {
	public Guid Id { get; set; } // autogenerated
	public string Title { get; set; } = null!;
	public string Description { get; set; } = null!;
	public MediaType Type { get; set; }
	public int ReleaseYear { get; set; }
	public short AgeRestriction { get; set; }
	public Guid CreatedBy { get; set; }
	public DateTimeOffset CreatedAt { get; set; } // autogenerated
	public DateTimeOffset UpdatedAt { get; set; } // autogenerated

	public AppUser? Creator { get; set; }
	public ICollection<MediaGenre> MediaGenres { get; set; } = new List<MediaGenre>();
	public ICollection<Rating> Ratings { get; set; } = new List<Rating>();
	public ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();
}