namespace Model.Entities;

public class Rating {
	public Guid Id { get; set; } // autogenerated
	public Guid MediaId { get; set; }
	public Guid UserId { get; set; }
	public short Stars { get; set; }
	public string? Comment { get; set; }
	public bool CommentConfirmed { get; set; }
	public DateTimeOffset CreatedAt { get; set; } // autogenerated
	public DateTimeOffset UpdatedAt { get; set; } // autogenerated

	public Media? Media { get; set; }
	public AppUser? User { get; set; }
	public ICollection<RatingLike> Likes { get; set; } = new List<RatingLike>();
}